### ISSUE TITLE
Workshop organisers able to cancel a workshop

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/planner#1251]
## Description of the issue 📄

Workshop organisers need to be able to mark a workshop as cancelled.

Have a checkbox in the admin area of the workshop, so that if an organiser cancels a workshop people can no longer RSVP, if people have RSVP'd they receive an email notifying them the workshop has been cancelled and a banner/note/something is shown on the workshop main page saying it's been cancelled.

### TODO

- [ ] Email workshop attendees notifying about workshop cancellation
- [ ] Add cancel button on admin page (I think this can be added on top toolbar rather than on edit  form, and include a confirmation step)
- [ ] Add note on workshop page
- [ ] Add note on admin workshop page
- [ ] Either don't acknowledge workshop attendances as missed, or remove attendees from workshop as part of cancellation step - after sending the cancellation email. The issue with this is that then we won't be able to track who was going to attend. On the other hand, if we remove them there will be no additional steps, like having to deal with making sure any emails are not sent out etc.
- [ ] Ensure that sponsors of cancelled events are not rendered in /sponsors and that sponsoring cancelled events is not counted as sponsorship in /admin/sponsors

## To do 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by notapatch** [comment]
This looks like a duplicate of #856 ? The work was stopped because the developers didn't know what to do with some of the [knock on effects of closing the workshop](https://github.com/codebar/planner/pull/1113#issuecomment-545701522)?

**Comment by despo** [comment]
@notapatch Thanks for the note on this.

I think as this is a bit higher priority at the moment (due to COVID and higher event cancellations) we can close the previous issue and keep this one open. I'll try and add more information to this issue as there are a couple of more things to take into account from sponsorships not being counted, to ignored missed attendances - that I can think of right now.

**Comment by notapatch** [comment]
- Add note on workshop page
  By note do you mean the same text for every cancelled event "Cancelled" or do you mean the admin should be able to set unique text "Cancelled due to Corvid 🐦 "  ?

**Comment by despo** [comment]
No the admin/organiser shouldn't have to do anything. The system should render a note about the workshop being cancelled e.g `This workshop has been cancelled` underneath the description, and probaly a `Cancelled` label component, using the warning foundation label so it's more prominent.
The label should also be visible in all places where the event is listed, eg Event/Landing page 'upcoming events', Chapter page

**Comment by notapatch** [comment]
Once a Workshop is cancelled there is no going back? You would have to send out emails again saying "my bad" and half the people wouldn't turn up as they were confused?


---
### Edit Form
 - I have not done anything on the create form - I can't think why anyone would cancel something they haven't created 🤔 

I've chosen a link because anything red and big would be distracting from the Primary button (which is grey).

- (Problem for later) The vertical alignment is wrong but not sure if I should fix at foundation level or write CSS class. 

![Screenshot 2020-05-15 at 16 43 02](https://user-images.githubusercontent.com/1710795/82069438-3500e500-96cb-11ea-8e29-9a281023e405.png)

**Comment by despo** [comment]
@notapatch 

1. Indeed there is no cancel email so one needs to be put in place, happy to review any text. It should be quite straightforward, something like 'The workshop/virtual workshop taking place at <date> has been cancelled (due to <reason> if a reason is supplied)' and an obvious email title so it's not missed. Maybe 'CANCELLED: ((workshop title))'

2. Cancelling a workshop should be irreversible and there is no need to cater for the scenario where it has been cancelled in error. As long as the confirmation popup is in place then that's all we need.

3. The confirmation popup is sufficient. The organisers are familiar with it and we use it in other places in the app as well so no need to overengineer this or introduce any JS (eg https://github.com/codebar/planner/blob/master/app/views/admin/members/show.html.haml#L12) 

4. I think it's more straightforward to check if an attendance has been cancelled based on the status of the workshop rather than having to update each individual workshop invitation to cancelled, which can potentially cause a workshop invitation and a workshop to be out of sync as well.

**Comment by despo** [comment]
@notapatch are you continuing work on this? Should I assign you to the issue?

**Comment by notapatch** [comment]
I am working on it. But I am taking the country roads by testing the classes I touch - currently testing WorkshopInvitation. If it's urgent you can take it off me, and I would understand completely, but otherwise I want to continue and you can assign me the issue - I except I will learn a lot from doing it.

[Keeping expectation low ... the works so far will be here so you can judge what's happening](https://github.com/notapatch/planner/pull/33). Feel free to comment on the work so far, what you want to see next, and esp if you think it's going in the wrong direction.

**Comment by notapatch** [comment]
### RSVPing

Looking at RSVPing within the system. I am assuming this is only effecting the Workshop RSVPing (there are routes for meeting, events and course).

#### RSVPing from Workshop

WorkshopsController contains two actions - #show and #rsvp. Show's view links to the rsvp action.

```ruby
# app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  def show
    @workshop = WorkshopPresenter.decorate(@workshop)

    render 'virtual_workshops/show' if @workshop.virtual?
  end
  ...
end
```

Below is the _actions partial used in Workshop#show's view clicking the buttons will route you through to the custom route workshops#rsvp

```ruby
#
# app/views/workshops/_actions.html.erb
# Prefix verb            URI Pattern                        Controller#Action
# rsvp_workshop POST     /workshops/:id/rsvp(.:format)      workshops#rsvp
#
- if @workshop.attendee?(current_user)
  = button_to "Manage your invitation", rsvp_workshop_path(@workshop), method: :post, class: 'button round '
- else
  - if current_user.student? && current_user.coach?
    = button_to "Attend as a student", rsvp_workshop_path(@workshop, role: "Student"), method: :post,class: 'button round '
    = button_to "Attend as a coach", rsvp_workshop_path(@workshop, role: "Coach"), method: :post,class: 'button round '
  - elsif current_user.student?
    = button_to "Attend as a student", rsvp_workshop_path(@workshop, role: "Student"), method: :post,class: 'button round '
  - elsif current_user.coach?
    = button_to "Attend as a coach", rsvp_workshop_path(@workshop, role: "Coach"), method: :post,class: 'button round '
  - else
    It looks like something went wrong while you were signing up.
    = link_to "Please tell us whether you want to attend as a student or coach.", subscriptions_path
```

#### app/views/workshop/show.html.haml
![Screenshot 2020-05-31 at 09 15 21](https://user-images.githubusercontent.com/1710795/83347792-63afca00-a31f-11ea-8329-5403123b2268.png)


The rsvp method assigns and invitation and redirects to `invitation#show`

```ruby
#
# Prefix verb            URI Pattern                     Controller#Action
# invitation GET        /invitation/:id(.:format)        invitation#show
#
class WorkshopsController < ApplicationController
  ...
  def rsvp
    redirect_to :back, notice: t('workshops.registration_not_open') unless @workshop.invitable_yet?

    if role_params.nil?
      @invitation = find_attending_invitation(@workshop, current_user)
    else
      if user_attending_or_waitlisted?(@workshop, current_user)
        return redirect_to :back, notice: t('workshops.already_wish_to_attend')
      end

      @invitation = find_or_create_invitation(@workshop, current_user, role_params)
    end

    redirect_to invitation_path(@invitation)
  end
  ...
end
```


```ruby
class InvitationController < ApplicationController
  ...
  def show
    @announcements = @invitation.member.announcements.active
    @tutorial_titles = Tutorial.all_titles

    @workshop = WorkshopPresenter.decorate(@invitation.workshop)

    render text: @workshop.attendees_csv if request.format.csv?
  end
  ...
end
```

#### app/views/invitation/show.html.haml
![Screenshot 2020-05-31 at 09 07 43](https://user-images.githubusercontent.com/1710795/83347647-39a9d800-a31e-11ea-9dc3-22974d5d51b0.png)

 WorkshopsController#show has an actions partial which has buttons that route to rsvp_workshop_path a custom route for wokshops#rvsp. Workshops#rsvp => Invitation#show

**Comment by notapatch** [comment]
### RSVPing starting from invite

Students and coaches are emails invites. And example of one is below. 

![Screenshot 2020-05-31 at 09 54 18](https://user-images.githubusercontent.com/1710795/83348462-c5266780-a324-11ea-9a46-aa6401a7185c.png)

The link is to `invitation#show`, like the workshop rsvp above and the rest of the pathway is identical.

#### app/views/workshop_invitation_mailer/invite_student.html.haml
```ruby
    Workshop
    %br
    %small #{humanize_date(@workshop.date_and_time, @workshop.ends_at, with_time: true)}
  = link_to 'View invitation and RSVP', full_url_for(invitation_url(@invitation)), class: 'btn'
%td{ width: '40%', style: 'vertical-align: top;'}
```

**Comment by notapatch** [comment]
## Invitation#show

```ruby
class InvitationController < ApplicationController
  ...
  def show
    @announcements = @invitation.member.announcements.active
    @tutorial_titles = Tutorial.all_titles

    @workshop = WorkshopPresenter.decorate(@invitation.workshop)

    render text: @workshop.attendees_csv if request.format.csv?
  end
  ...
end
```

#### app/views/invitation/show.html.haml
![Screenshot 2020-05-31 at 09 07 43](https://user-images.githubusercontent.com/1710795/83347647-39a9d800-a31e-11ea-9dc3-22974d5d51b0.png)

 WorkshopsController#show has an actions partial which has buttons that route to rsvp_workshop_path a custom route for wokshops#rvsp. Workshops#rsvp => Invitation#show
