### ISSUE TITLE
Display timezone on all types of events

### ISSUE THREAD

**Issue by despo** [codebar/planner#1272]
## Description of the issue 📄
Easy fix until we can identify the work required to localise the website depending on user's preference, request IP or browser timezone.

#TODO
Ensure timezone is displayed on:
- [ ] Landing page 'upcoming events'
- [ ] Events page 'Upcoming and past events'
- [ ] Workshop page
- [ ] Workshop invitation page
- [ ] Workshop and virtual workshop emails 
    - [ ] invitation
    - [ ] attendance
    - [ ] attendance reminder
    - [ ]  waiting list emails
 - [ ] Admin workshop page
- [ ] Meeting page
- [ ] Meeting admin page
- [ ] Event pge
- [ ] Event admin page
- [ ] Course page
- [ ] Course admin page

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [x] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member
