### ISSUE TITLE
Improve tracking of what happens to an invite. 

### ISSUE THREAD

**Issue by creature** [codebar/planner#207]
When someone signs to a Codebar group, we generate an invite for them each week. That invite can be in a number of states: 
1. No response (they haven't done anything yet)
2. Attending (sets the `attending` field to true).
3. Attended (sets the `attended` field to true). 

(We also keep track of a waiting list in a separate database table.)

Members can manage their attendance through the website or via the invite email. For instance, if an attendee can't make it any more they can set themselves back to state 1 by clicking "I can no longer attend", which sets the `attending` field to false. When someone shows up at a workshop, we click a button that sets the `attended` field to true. If someone emails to cancel, we click the "Not attending" button (which sets the `attending` field to false).

This works OK. We can track who comes to the workshop, manage the waiting list, and send out reminders to attendees and people on the waiting list. But there's some questions we can't answer: 
- Who signed up to attend, and then just didn't show up? 
- Who emailed to let us know they can't make it, but did so at really short notice? 
- Who showed up who didn't have a place? 
- How quickly do workshops fill up? 
- How big was the waiting list, at its maximum? 
- Who makes a habit of doing any of the above? 

---

To answer these questions, we need to keep track of an invite's state, and log the transitions between them. We _could_ solve this problem by sprinkling a lot of boolean attributes & timestamps on the `SessionInvitation` model, but I think we should make it an explicit state machine instead. Here's my initial thinking: 

![img_0730](https://cloud.githubusercontent.com/assets/244541/6269716/f7a18d0c-b84c-11e4-9837-0cd3d36cbdff.JPG)

I don't think we should worry about the 'Not attending' case for now, so there's 6 states. An invite would have an initial state of "invited". The grey arrows are the transitions necessary to track people who aren't on the attendee list. 

Here's an attempt at subtasking this: 
- [ ] Add the [aasm gem](https://github.com/aasm/aasm) to the project, and add it to the `SessionInvitation` model
- [ ] Configure the transitions on the `SessionInvitation` model
- [ ] Add a model to log transitions - it would need to track the invitation, starting state, ending state, and timestamp. 
- [ ] Update the admin interface so the buttons trigger a state transition, and add the ability to mark someone as a no-show or a short notice cancellation. 
- [ ] Update the invite view so the buttons trigger a state transition
- [ ] Update the workshop view so the buttons trigger a state transition
- [ ] **EITHER** rip out the existing waiting list table in favour of using the state machine, **OR** ensure that when the waiting list changes the invite also gets a state transition. 
- [ ] Migrate the existing data to the state machine, as best as we can
- [ ] Display the state transition log on the admin member page
- [ ] Tests for all of the above

This looks like a big bit of work! I'm happy to take it on, but if anyone has any feedback or comments this is a great time to give your input. :)

**Comment by despo** [comment]
I think this is over-engineered. The only issue we have is automating the waiting list trigger - or rather fixing the admin routes - and adding a boolean field so we know if someone did not attend as the current functionality works.

**Comment by barisbalic** [comment]
Devils advocate for both sides TBH.  Long-term using a state-machine makes sense, but I also don't think the reasons for doing it hold up right now.  Most of the answers feel like things you'd look at, like or dislike, then forget until next time.

**Comment by creature** [comment]
I don't think it's as complex as it looks; it just has several touchpoints. The approach outlined above only adds 1 field, `state`, to the `SessionInvitation` - and there's only 5 possible values for it. (It would also let us retire the `WaitingList` table, but with the introduction of another one of similar complexity - so no net change). I also think it's easier to figure out the state of a `SessionInvitation` with an explicit state machine, rather than trying to figure it out from a combination of boolean flags and timestamps.

But the main reason I'm volunteering to do this is because it's information I think we need. Being able to show growing demand for our workshops is needed to get more sponsorship & achieve Codebar's long-term goals. Tracking how long it takes for a workshop to fill up & the waiting list size does that. I think these numbers would also help us with planning Codebar West, Codebar South, etc. 
I can also recall numerous conversations amongst the London organisers where we try to figure out if someone's been a no-show several times, or if they always sign up for a place then drop out at the last moment, or if we're imagining it. Most of the time we can't remember. I'd much rather have the app track it for us. 
We know more people want to come to Codebar than we can accommodate, which is why we try to discourage no-shows and late cancellations. I'm happy emailing people manually to ask them to change their behaviour, but I'd like more information about what that behaviour *is*. That helps me write better messages, and that means we have more attendees, which means more people are learning.

I think these are all real problems that we'd like to tackle, and I'm happy to do the work to tackle them.

**Comment by barisbalic** [comment]
You would need to write tasks for back-filling data if you want to maintain any history, worth keeping in mind.

I don't think those numbers would help that much, they might be interesting, but I don't think they would change much at all.  People either want to sponsor or they don't, and you can ball-park most of those figures well enough to tell sponsors if you want to give them "data".  It seems hugely unlikely that saying 'We have around 30 people on the waiting list' would have more or less impact than 'We have an average of 32 people on the waiting list'.  Same for ramping up other chapters, which is probably best done by running the first event instead.

The ability to stop no-shows from turning up makes the most sense to implement sooner rather than later, the rest feels a bit week.  Also I wasn't trying to say it shouldn't happen at all, just that if it's a choice between that or https://github.com/codebar/planner/issues/193 (which you yourself posted) one has tangible, immediate benefit.

**Comment by creature** [comment]
> You would need to write tasks for back-filling data if you want to maintain any history

Yep! That's included on the list of subtasks, and I don't think it's going to be that difficult. 'invited' is the default state, so the backfill is going to be along these lines: 

    SessionInvitation.where(attended: true).each {|i| i.update_attribute(:aasm_state, 'attended')}
    SessionInvitation.where(attending: true, attended: false).each {|i| i.update_attribute(:aasm_state, 'attending')}
    WaitingList.all.each {|wl| wl.invitation.update_attribute(:aasm_state, 'waitlisted')}

We can go back and click the no-show button if necessary, but I think it would also be fine to only track that info going forward.

> People either want to sponsor or they don't... It seems hugely unlikely that saying 'We have around 30 people on the waiting list' would have more or less impact than 'We have an average of 32 people on the waiting list'.

You're right - in those cases, it's unlikely to have an impact. We're lucky to have a lot of companies who want to sponsor our week-to-week meetings by providing a venue & food, and they're all happy to help out to their capacities. But there's been a number of longer-range options & ideas floated that would need more substantial sponsorship/investment. Being able to show growing demand & a growing audience would make that easier to secure.

**Comment by barisbalic** [comment]
Again I think you can approximate most of those answers well enough to not need to write code to support it.  I also think given the ebb and flow it would be hard to conclusively say things like the audience has grown, although this is highly speculative on my part.

**Comment by docljn** [comment]
Hello the team. In the spirit of CodeTriage, is this issue still current/actionable or should it be closed for now? Thank you.

**Comment by barisbalic** [comment]
Yeah, I think given it's been stagnant for a couple of years it's safe to put it to bed!  Thanks for keeping things tidy 👍

**Comment by docljn** [comment]
I’ll need an admin to do the closing...

**Comment by docljn** [comment]
Thank you.
