### ISSUE TITLE
Ability to edit organisers on new workshop page

### ISSUE THREAD

**Issue by matyikriszta** [codebar/planner#625]
## Description 📄

When and admin creates a new workshop, there is no way to add/remove organisers from the new workshop page (admin/workshops/new). We would like to include this functionality in the form and we would like it to work the same way as it does on the edit workshop page (/admin/workshops/:id/edit).

## Screenshots 📷

![codebar io_admin_workshops_new laptop with mdpi screen](https://user-images.githubusercontent.com/5873816/33223542-60d99338-d158-11e7-9421-f5c53601af49.png)
![codebar io_admin_workshops_628_edit laptop with mdpi screen](https://user-images.githubusercontent.com/5873816/33223556-6af49782-d158-11e7-8873-d92303b26256.png)

## Steps to fix 🛠

The new workshop form can be found under `app/views/admin/workshops/_form.html.haml`. Take a look at the edit form at `app/views/admin/workshops/_edit_form.html.haml` and re-create the Organiser section. As an additional step maybe merge these two forms together?

## Todo 📋

* [ ] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request, make sure you mention #codebar24PR2017 in the description
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

**Comment by koskoci** [comment]
I'd like to take this on - my first open source feature! However, I'm having trouble setting up the project locally. Specifically, I can run the app but running the seeds fails. Could someone please help me out with this? I've posted my issue in the ruby channel on the codebar slack. Thanks in advance!

**Comment by koskoci** [comment]
I am all set, thanks! Working on this.

**Comment by despo** [comment]
I think a better way to tackle this is to move workshop creation under `/admin/chapter/:id/workshops/new`. 

Initially the current route (`/admin/workshops/new`) was exposed as the app was admin centric, but now organisers are the ones creating new workshops on a weekly basis. Also, having knowledge of the chapter that wants to create the workshop upfront means that we know who the organisers are and don't require any JS to set anything else up.
